import path from "path";
import fs from "fs";
import { randomUUID } from "crypto";
import { generateApprovalNote } from "../../../../ai-service/reports/approval-note.service.js";
import { getReportStoragePath, getOrganizationGeneratedDir } from "../../utils/storage.js";
import { createReport } from "../../repositories/reports.repository.js";

export class DocumentGenerateError extends Error {
    constructor(message) {
        super(message);
        this.name = "DocumentGenerateError";
    }
}

/**
 * Generates an Approval Note DOCX from structured sections.
 *
 * @param {object} args
 * @param {string} [args.title="Approval Note"] - Subject/title of the deliverable
 * @param {Array<{heading: string, content: string}>} args.sections - Structured report sections
 * @param {object} [context={}] - Execution context containing authoritative organizationId
 * @returns {Promise<{ filename: string, downloadUrl: string, title: string, sectionsCount: number, status: string, reportId?: string }>}
 */
export async function executeDocumentGenerate(args, context = {}) {
    if (!args || typeof args !== "object") {
        throw new DocumentGenerateError("Arguments must be an object containing 'sections'");
    }

    const organizationId = context?.organizationId;
    if (!organizationId || typeof organizationId !== "string" || !organizationId.trim()) {
        throw new DocumentGenerateError("Execution context missing authenticated organizationId for document generate");
    }

    // Explicitly ignore any organizationId in args to prevent LLM spoofing
    const {
        title = "Approval Note",
        subject,
        sections,
        findings,
        technicalAnalysis: directAnalysis,
        riskAssessment,
        recommendation: directRec,
        citations,
        background: directBackground,
    } = args;

    if ((!Array.isArray(sections) || sections.length === 0) && (!Array.isArray(findings) || findings.length === 0)) {
        throw new DocumentGenerateError("Arguments must contain 'sections' or 'findings'");
    }

    // Adapt sections/findings into the Approval Note schema expected by generateApprovalNote
    let background = directBackground || "Generated by SovereignAI Autonomous Agent.";
    let technicalAnalysis = directAnalysis || "";
    let recommendation = directRec || "Review findings and proceed with recommended maintenance.";
    let riskReason = riskAssessment?.reason || "Identified operational and safety considerations.";
    let riskLevel = riskAssessment?.level || "MEDIUM";
    const findingsList = [];

    if (Array.isArray(findings) && findings.length > 0) {
        findingsList.push(...findings);
    }

    if (Array.isArray(sections)) {
        for (const sec of sections) {
            const heading = (sec.heading || "").toLowerCase();
            const content = (sec.content || "").trim();

            if (heading.includes("background") || heading.includes("summary")) {
                background = content;
            } else if (heading.includes("finding") || heading.includes("defect") || heading.includes("observation")) {
                if (findingsList.length === 0) {
                    findingsList.push({
                        finding: content,
                        equipment: "Critical Equipment",
                        severity: "Medium",
                        evidence: content,
                    });
                }
            } else if (heading.includes("risk")) {
                riskReason = content;
                if (content.toLowerCase().includes("high")) riskLevel = "HIGH";
                else if (content.toLowerCase().includes("low")) riskLevel = "LOW";
            } else if (heading.includes("recommendation") || heading.includes("action")) {
                recommendation = content;
            } else {
                technicalAnalysis += `${sec.heading}:\n${content}\n\n`;
            }
        }
    }

    if (findingsList.length === 0) {
        findingsList.push({
            finding: (sections && sections[0]?.content) || "No critical findings recorded",
            equipment: "Plant Equipment",
            severity: "Medium",
            evidence: (sections && sections[0]?.content) || "Report completed.",
        });
    }

    const resolvedCitations = Array.isArray(citations) && citations.length > 0
        ? citations
        : [
            {
                filename: "SovereignAI_Knowledge_Base",
                page: 1,
                chunkIndex: 0,
            },
        ];

    const normalizedRiskLevel =
        riskLevel === "Not Determined" || riskLevel === "NOT DETERMINED" || !riskLevel
            ? null
            : String(riskLevel).toUpperCase();

    const approvalNoteData = {
        subject: typeof (subject || title) === "string" && (subject || title).trim() ? (subject || title).trim() : "Approval Note",
        background,
        findings: findingsList,
        technicalAnalysis: technicalAnalysis.trim() || "Multi-step automated agent assessment.",
        riskAssessment: {
            level: normalizedRiskLevel,
            reason: riskReason,
        },
        recommendation,
        citations: resolvedCitations,
    };

    // Ensure output directory exists inside tenant-scoped generated storage
    const cleanOrgId = organizationId.trim();
    getOrganizationGeneratedDir(cleanOrgId, { create: true });

    const filename = `Approval_Note_Agent_${randomUUID().slice(0, 8)}.docx`;
    const outputPath = getReportStoragePath(cleanOrgId, filename);

    try {
        await generateApprovalNote(approvalNoteData, { outputPath });

        // Persist report record in PostgreSQL bound strictly to authenticated organization
        let reportRow = null;
        try {
            reportRow = await createReport({
                organizationId: cleanOrgId,
                title: approvalNoteData.subject,
                filename,
                riskLevel: normalizedRiskLevel,
                status: "GENERATED",
                task: "Agent document_generate",
            });
        } catch (dbErr) {
            console.warn(`[documentGenerate.tool] Warning: Failed to persist report record in DB: ${dbErr.message}`);
        }

        return {
            filename,
            downloadUrl: `/api/v1/inspection/download/${filename}`,
            title: approvalNoteData.subject,
            sectionsCount: Array.isArray(sections) ? sections.length : findingsList.length,
            status: "Generated",
            reportId: reportRow?.id || null,
        };
    } catch (docxErr) {
        throw new DocumentGenerateError(`Failed to generate DOCX deliverable: ${docxErr.message}`);
    }
}

